language: python
matrix:
  include:
  - python: "2.7"
    env: TEST_SUITE=py.test
  - python: "3.4"
    env: TEST_SUITE=py.test
  - python: "3.5"
    env: TEST_SUITE=py.test
  - python: "3.6"
    env: TEST_SUITE=py.test
  - python: "pypy"
    env: TEST_SUITE=py.test
  - python: "pypy3.5-5.8.0"
    env: TEST_SUITE="py.test test_fuzzywuzzy.py test_fuzzywuzzy_pytest.py"
install:
  - pip install pytest pycodestyle
  - if [ $TRAVIS_PYTHON_VERSION != "pypy3" ]; then pip install hypothesis; fi;
script:
  - $TEST_SUITE
notifications:
  on_success: always
